services:
  ticket-tracer-api:
    build:
      context: .
      dockerfile: TicketTracer.Api/Dockerfile
    container_name: ticket-tracer-api
    ports:
      - "8080:8080"
    networks:
      - monitoring
    volumes:
      - ./TicketTracer.Api/logs:/app/logs:z # chmod 644 -R ./TicketTracer.Api/logs
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:v3.3.0-rc.1
    container_name: ticket-tracer-prometheus
    user: "65534"
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/data:/prometheus:z
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z,ro # chmod 647 -R prometheus
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.6.0
    container_name: ticket-tracer-grafana
    user: "472"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=qwuipss
      - GF_SECURITY_ADMIN_PASSWORD=qwuipss!
    volumes:
      - ./grafana/data:/var/lib/grafana:z # chmod 647 -R grafana
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge